### PR TITLE
Hover on categories in home page

### PR DESCRIPTION
**Pull request by KamilWo**
New descriptions placements.
Pictograms on hover - they are on our server now.
Script changes images src's for green hover.
Images should have 'off' and 'on' in names, when they are put in place 
by Odoo 'Edit' WebBuilder function.

### CODE REVIEW

**Comment by KrzysiekJ** [comment]
This pull request has conflict(s).

**Comment by KrzysiekJ** [comment]
This pull request has conflict(s).

**Comment by KamilWo** [comment]
Conflicts resolved.

**Comment by KrzysiekJ** [comment]
Merged in bedcac554a7e7ea9b374570cbfa938d921a408c8.

**Pull request closed without merging**
